### ISSUE TITLE
Document issues with `@babel/env` preset

### ISSUE THREAD

**Issue by singingwolfboy** [eropple/taskbotjs#12]
I was using the [`@babel/env`](https://babeljs.io/docs/en/babel-preset-env) preset in my project, and ran into a problem when trying to execute jobs:

```
[2018-09-11T19:31:52.559Z] ERROR: consumer/Worker/87336 on mammoth.local: Error in job execution. (jobId=surpass-stingray-9a6944)
    TypeError: Class constructor Job cannot be invoked without 'new'
        at new ReadFileTask (/Users/singingwolfboy/clones/friendmap-api/lib/task/ReadFile.js:42:75)
        at Worker.start (/Users/singingwolfboy/clones/friendmap-api/node_modules/@taskbotjs/service/dist/Server/Worker.js:37:25)
        at process._tickCallback (internal/process/next_tick.js:68:7)
```

I found [this StackOverflow answer](https://stackoverflow.com/a/51860850/141395) that lead me to believe that `@babel/env` was the problem. I changed my Babel configuration so that it now looks like this:

```json
"presets": [
  [
    "@babel/env",
    {
      "targets": {
        "node": "current"
      }
    }
  ],
  "@babel/typescript"
]
```

And now the worker process can process jobs correctly! This should really be mentioned in the documentation.

**Comment by eropple** [comment]
Interesting. I am pretty exclusively a user of the TypeScript compiler straight-out, rather than Babel. Wasn't aware you could actually combine the two. This is an interesting one I need to dig into a little more, but your short-term fix is a good one and when I get back home I'll elaborate upon it. Thanks.
