### ISSUE TITLE
`No valid rules have been specified for TypeScript files` error

### ISSUE THREAD

**Issue by gtirloni** [eropple/taskbotjs#2]
After installing Typescript, Yarn, jest and tslint manually (please consider adding as devDependencies), this is the error I get running `yarn run test`:

```
$ npm run test

> @taskbotjs/workspace@0.9.1-wip test /home/user/tmp/taskbotjs
> oao run-script test

2018-07-06T15:37:41.094Z           storyboard INFO  ┌── ROOT STORY: Node.js 10.6.0 on Linux 64-bit, SB 3.1.3 [CREATED]
2018-07-06T15:37:41.095Z           storyboard INFO  Log filter: *:DEBUG
2018-07-06T15:37:41.291Z                 main INFO  Reading all package.json files...
2018-07-06T15:37:41.293Z                 main INFO  ┌── Run cmd yarn run test at service [CREATED]
2018-07-06T15:37:41.611Z                 yarn INFO  yarn run v1.7.0
2018-07-06T15:37:41.676Z                 yarn INFO  $ tslint --project . && jest
2018-07-06T15:37:42.752Z                 yarn ERROR No valid rules have been specified for TypeScript files
2018-07-06T15:37:42.969Z                 yarn ERROR ● Validation Error:
2018-07-06T15:37:42.969Z                 yarn ERROR   Module ts-jest in the transform option was not found.
2018-07-06T15:37:42.969Z                 yarn ERROR          <rootDir> is: /home/user/tmp/taskbotjs/service
2018-07-06T15:37:42.969Z                 yarn ERROR   Configuration Documentation:
2018-07-06T15:37:42.969Z                 yarn ERROR   https://facebook.github.io/jest/docs/configuration.html
2018-07-06T15:37:42.973Z                 yarn ERROR error Command failed with exit code 1.
2018-07-06T15:37:42.974Z                 yarn INFO  info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2018-07-06T15:37:42.980Z                 yarn INFO  
2018-07-06T15:37:42.981Z                 main ERROR Command 'yarn run test' failed [1] at service
2018-07-06T15:37:42.982Z                 main INFO  └── Run cmd yarn run test at service [CLOSED]
{ Error: Command 'yarn run test' failed [1] at service
    at execError (/home/user/tmp/taskbotjs/node_modules/oao/lib/utils/shell.js:193:13)
    at _callee2$ (/home/user/tmp/taskbotjs/node_modules/oao/lib/utils/shell.js:173:20)
    at tryCatch (/home/user/tmp/taskbotjs/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/home/user/tmp/taskbotjs/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as throw] (/home/user/tmp/taskbotjs/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/home/user/tmp/taskbotjs/node_modules/oao/lib/utils/shell.js:28:191)
    at /home/user/tmp/taskbotjs/node_modules/oao/lib/utils/shell.js:28:402
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 1,
  stdout:
   'yarn run v1.7.0\n$ tslint --project . && jest\ninfo Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.\n',
  stderr:
   'No valid rules have been specified for TypeScript files\n● Validation Error:\n\n  Module ts-jest in the transform option was not found.\n         <rootDir> is: /home/user/tmp/taskbotjs/service\n\n  Configuration Documentation:\n  https://facebook.github.io/jest/docs/configuration.html\n\nerror Command failed with exit code 1.\n' }
2018-07-06T15:37:42.985Z           storyboard INFO  └── ROOT STORY: Node.js 10.6.0 on Linux 64-bit, SB 3.1.3 [CLOSED]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @taskbotjs/workspace@0.9.1-wip test: `oao run-script test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @taskbotjs/workspace@0.9.1-wip test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2018-07-06T15_37_42_992Z-debug.log
```

```
$ tsc --version
Version 2.9.2

$ node -v
v10.6.0

$ npm -v
6.1.0

$ yarn -v
1.7.0
```

**Comment by eropple** [comment]
They should be dev dependencies, but they should also be executed via `yarn exec`. Case of Works On My Machine; this is good feedback and I'll get to that ASAP. Thank you!
